# Frontend to dune.

.PHONY: default build install uninstall utop test clean

default: build

build:
	jbuilder build

test:
	jbuilder runtest -f

install:
	jbuilder install

uninstall:
	jbuilder uninstall

clean:
	jbuilder clean
