# Invoke `make all` to build, `make clean` to clean up, etc.
# If you want to use make, you can run the commands directly
# such as `jbuilder build @install`

# Build
all:
	jbuilder build @install

.PHONY: clean all test

# Build and run tests
test:
	jbuilder runtest

# Clean up
clean:
	jbuilder clean
